//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminLogin
    {
        public int Serial { get; set; }
        [Required(ErrorMessage = "please fill up the First name")]
        [MinLength(3)]
        [Display(Name = "Fname")]
        public string Fname { get; set; }
        [Required(ErrorMessage = "please fill up the Last name")]
        
        [MinLength(3)]
        [Display(Name = "Lname")]
        public string Lname { get; set; }
        [Required(ErrorMessage = "please fill up the Mobile number")]
        
        [MinLength(3)]
        [Display(Name = "Mobile_no")]
        public string Mobile_no { get; set; }
        [Required(ErrorMessage = "please fill up the Id number")]
        
        
        [Display(Name = "Id_number")]
        public int Id_number { get; set; }
        [Required(ErrorMessage ="please fill up the Username" )]
        
        [MinLength(3)]
        [Display(Name="Username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "please fill up the Password")]
        
        [MinLength(3)]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        
        public string Password { get; set; }
        [Required(ErrorMessage = "please fill up the Data")]
        
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public string Date { get; set; }

        public int Type { get; set; }
    }
}
