//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Agencymoney
    {
        public int Serial { get; set; }
        [Required(ErrorMessage = "please fill up the  name")]

        [MinLength(3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "please fill up the  Agency name")]

        [MinLength(3)]
        [Display(Name = "Agency_name")]
        public string Agency_name { get; set; }
        [Required(ErrorMessage = "please fill up the  Date")]

        [MinLength(3)]
        [Display(Name = "Date")]
        public string Date { get; set; }
        [Required(ErrorMessage = "please give the amount")]

        
        [Display(Name = "Money")]
        public int Money { get; set; }
    }
}
