//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminLogin> AdminLogins { get; set; }
        public DbSet<AgencyLogin> AgencyLogins { get; set; }
        public DbSet<Agencymoney> Agencymoneys { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserFrom> UserFroms { get; set; }
        public DbSet<UserLogin> UserLogins { get; set; }
        public DbSet<Usermoney> Usermoneys { get; set; }
        public DbSet<VolunteerFrom> VolunteerFroms { get; set; }
        public DbSet<VolunteerLogin> VolunteerLogins { get; set; }
        public DbSet<Voluteenerror> Voluteenerrors { get; set; }
    }
}
