//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserLogin
    {
        public int Serial { get; set; }
        [Required(ErrorMessage = "Name is required!")]

        [MinLength(3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "please fill up the Mobile Number")]
        [Display(Name = "Mobile_number")]
        public int Mobile_number { get; set; }
        [Required(ErrorMessage = "User Name is required!")]

        [MinLength(3)]
        [Display(Name = "Username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password is required!")]

        [MinLength(3)]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]

        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "please fill up the Data")]

        [Display(Name = "Date")]
        public string Date { get; set; }
        public int Type { get; set; }
    }
}
