//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usermoney
    {
        public int Serial { get; set; }
        [Required(ErrorMessage = "please fill up the  name")]
        [StringLength(8, ErrorMessage = "your max limit is 8")]
        [MinLength(3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "please fill up the  Date")]
        
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public string Date { get; set; }
        [Required(ErrorMessage = "please fill up the amount")]
        [Display(Name = "Money")]
        public int Money { get; set; }
    }
}
