//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserFrom
    {
        public int Serial { get; set; }
        [Required(ErrorMessage = "please fill up the  name")]
        
        [MinLength(3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "please fill up the  Mobile name")]
        
        [Display(Name = "mobile_number")]
        public int mobile_number { get; set; }
        [Required(ErrorMessage = "please fill up the  orphan name")]
        
        [MinLength(3)]
        [Display(Name = "Orphan_name")]
        public string Orphan_name { get; set; }
        [Required(ErrorMessage = "please fill up the  Location")]
        
        [MinLength(3)]
        [Display(Name = "Location")]
        public string Location { get; set; }
        [Required(ErrorMessage = "please fill up the  Date")]
        
        [MinLength(3)]
        [Display(Name = "Date")]
        
        public string Date { get; set; }
        public int Volenserial { get; set; }
    
        public virtual VolunteerLogin VolunteerLogin { get; set; }
    }
}
