//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midproject.Models.En
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VolunteerFrom
    {
        public int Serial { get; set; }
        [Required(ErrorMessage = "please fill up the  name")]
        
        [MinLength(3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "please fill up the nid name")]
        
        [Display(Name = "nId_number")]
        public int nId_number { get; set; }
        [Required(ErrorMessage = "please fill up the userserial")]
        
        [Display(Name = "Userserial")]
        public int Userserial { get; set; }
        public int Orphanserial { get; set; }
    
        public virtual AgencyLogin AgencyLogin { get; set; }
    }
}
